local Widget = require("lapis.html").Widget

return Widget:extend(function(self)
  html_5(function()
    head(function()
      meta({ charset = "UTF-8" })
      meta({ name = "viewport", content = "width=device-width, initial-scale=1.0" })
      title("Portal Gamer")
      link({ rel = "stylesheet", href = "/static/style.css" })
      link({ href = "https://fonts.googleapis.com/css2?family=Inter:wght@400;600;800&display=swap", rel = "stylesheet" })
    end)
    body(function()
      header({ class = "site-header" }, function()
        div({ class = "container header-inner" }, function()
          h1("🎮 Portal Gamer")
          nav(function()
            a({ href = "/" }, "Início")
            a({ href = "/ranking" }, "Ranking")
          end)
        end)
      end)
      main({ class = "container content-area" }, function()
        self:content_for("inner")
      end)
      footer({ class = "site-footer" }, function()
        div({ class = "container" }, function()
          p("© 2026 Portal Gamer - Desenvolvido em Lua com Lapis")
        end)
      end)
    end)
  end)
end)